server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /
      suffix: .html
  #不要为我们工程中的资源文件建立映射##注意:使用
#  resources:
#    add-mappings: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl