server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.moon.model.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.moon.mapper: debug
